# -*- coding: utf-8 -*-
"""Aimed.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lpo8mYgX4Iktvy7K8KtXs7hAI8wtvwh8
"""

!pip install transformers accelerate gradio --quiet



# ===============================================================
# AI MEDICAL PRESCRIPTION VERIFICATION SYSTEM
# Leveraging IBM Granite 3.3 2B Instruct + Hugging Face + Gradio
# ===============================================================

# ----------------- INSTALL DEPENDENCIES -----------------
!pip install transformers accelerate gradio --quiet

# ----------------- IMPORT LIBRARIES ---------------------
from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline
import gradio as gr
import torch

# ----------------- HUGGING FACE TOKEN -------------------
# IMPORTANT: Replace with your Hugging Face API Key
HF_TOKEN = "YOUR_HUGGINGFACE_API_KEY_HERE"

# ----------------- LOAD MODEL ---------------------------
model_name = "ibm-granite/granite-3.3-2b-instruct"

tokenizer = AutoTokenizer.from_pretrained(model_name, use_auth_token=HF_TOKEN)

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    torch_dtype=torch.float16,
    device_map="auto",
    use_auth_token=HF_TOKEN
)

pipe = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    max_new_tokens=500,
    temperature=0.1,
    top_p=0.9
)

# ----------------- AI PROCESSING FUNCTION ---------------
def analyze_prescription(prescription, patient_age):
    prompt = f"""
You are a medical AI assistant specialized in prescription verification.
Analyze the prescription using medical reasoning. Your task:

### 1. Extract Drug Information (NLP)
- List medications
- Extract strength, dosage, frequency, and duration

### 2. Drug Interaction Check
- Identify possible interactions between medications
- Explain severity (mild, moderate, severe)

### 3. Age-Specific Dosage Analysis
- Check whether dosage fits a patient aged {patient_age}
- Mention if dosage is too high, too low, or appropriate

### 4. Suggest Alternative Medications
- Suggest safer or equivalent alternatives if needed
- Explain why they may be beneficial

### 5. Summarize Overall Prescription Safety
- Give a final verdict (SAFE / NEEDS REVIEW / UNSAFE)

### Prescription to evaluate:
\"\"\"{prescription}\"\"\"

Respond in a clear, structured medical report format.
IMPORTANT: Do NOT give actual medical advice. Only analyze based on general information.
"""

    result = pipe(prompt)[0]["generated_text"]
    return result


# ----------------- GRADIO INTERFACE ---------------------
ui = gr.Interface(
    fn=analyze_prescription,
    inputs=[
        gr.Textbox(label="Enter Prescription Text", lines=8, placeholder="e.g., Amoxicillin 500 mg twice daily + Ibuprofen 400 mg as needed"),
        gr.Number(label="Patient Age", value=30)
    ],
    outputs=gr.Textbox(label="AI Medical Analysis Report", lines=20),
    title="AI Medical Prescription Verification",
    description="Powered by IBM Granite 3.3 2B Instruct + Hugging Face",
)

# ----------------- LAUNCH APP ---------------------------
ui.launch()